# Generated by Django 4.1 on 2022-11-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('phonenumber', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('pincode', models.BigIntegerField(default=0)),
                ('district', models.CharField(choices=[('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Kannur', 'Kannur'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Kollam', 'Kollam'), ('Ernakulam', 'Ernakulam'), ('Wayanad', 'Wayanad'), ('Kasaragod', 'Kasaragod'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('None', 'None')], default='None', max_length=50)),
                ('role', models.CharField(choices=[('is_admin', 'is_admin'), ('is_child', 'is_child'), ('is_ashaworker', 'is_ashaworker'), ('is_hospital', 'is_hospital'), ('is_PHC', 'is_PHC')], max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('is_ashaworker', models.BooleanField(default=False)),
                ('is_hospital', models.BooleanField(default=False)),
                ('is_PHC', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='addvaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinename', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_addprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathersname', models.CharField(max_length=20)),
                ('mothersname', models.CharField(max_length=30)),
                ('panchayath', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('weight', models.BigIntegerField()),
                ('dob', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='addvaccinedate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinedate', models.DateField(default=0)),
                ('vaccinetime', models.CharField(max_length=200)),
                ('vaccinename', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.addvaccine')),
            ],
        ),
    ]
