# Generated by Django 4.1 on 2022-11-18 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_stock',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
        migrations.AlterField(
            model_name='userprofile_update',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
    ]
