# Generated by Django 4.1 on 2022-11-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccinedate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinedate', models.DateField(default=0)),
                ('vaccinetime', models.CharField(max_length=200)),
                ('vaccinename', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.addvaccine')),
            ],
        ),
    ]
