# Generated by Django 4.1 on 2022-11-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vaccinedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addvaccinedate',
        ),
    ]
