# Generated by Django 4.1 on 2022-11-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_timeslot',
            name='hospital_name',
            field=models.CharField(default='000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='new_stock',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
