# Generated by Django 4.1 on 2022-11-20 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_timeslot_hospital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.AlterField(
            model_name='userprofile_update',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=200)),
                ('dose', models.BigIntegerField()),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('hospital_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.new_stock')),
                ('time_slot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.add_timeslot')),
            ],
        ),
    ]
