# Generated by Django 4.1 on 2022-11-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_feedbacks_dob_alter_update_profile_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
