# Generated by Django 4.1 on 2022-11-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_booking_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking_add',
        ),
    ]
