# Generated by Django 4.1 on 2022-11-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_booking_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='000000', max_length=200)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=200)),
                ('dose', models.BigIntegerField()),
                ('time_slot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.add_timeslot')),
                ('vaccination_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.new_stock')),
            ],
        ),
    ]
