# Generated by Django 4.1 on 2022-11-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_book_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_add',
            name='child_name',
            field=models.CharField(default='000000', max_length=200),
        ),
    ]
