# Generated by Django 4.1 on 2022-11-23 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_feedbacks_dob_alter_update_profile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_add',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book_add',
            name='vaccine_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.add_vaccines'),
        ),
    ]
