# Generated by Django 4.1 on 2022-11-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_book_add_user_alter_book_add_vaccine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vaccines',
            name='side_effects',
        ),
    ]
