# Generated by Django 4.1 on 2022-11-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_add_timeslot_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_add',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='add_timeslot',
        ),
    ]
