# Generated by Django 4.1 on 2022-11-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_time_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_slot',
            old_name='time_slot',
            new_name='time_slots',
        ),
    ]
