# Generated by Django 4.1 on 2022-11-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_time_slot_time_slot_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_add',
            name='time_slots',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.time_slot'),
        ),
    ]
