# Generated by Django 4.1 on 2023-02-21 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_book_add_time_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_hospitaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 2, 21)),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 2, 21)),
        ),
        migrations.AlterField(
            model_name='userprofile_update',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 2, 21)),
        ),
    ]
