# Generated by Django 4.1 on 2023-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_type_add_hospitaldetails_hos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_hospitaldetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
