# Generated by Django 4.1 on 2023-02-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_add_hospitaldetails_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_hospitaldetails',
            old_name='hospital_name',
            new_name='hosp_name',
        ),
    ]
