# Generated by Django 4.1 on 2023-02-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_book_add_amount_alter_feedbacks_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_stock',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
